[2025-08-19T05:27:08.679+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T05:27:08.711+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: chained_tasks_dag.simulate_file_confirmation manual__2025-08-19T05:27:02.191089+00:00 [queued]>
[2025-08-19T05:27:08.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: chained_tasks_dag.simulate_file_confirmation manual__2025-08-19T05:27:02.191089+00:00 [queued]>
[2025-08-19T05:27:08.724+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-19T05:27:08.747+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): simulate_file_confirmation> on 2025-08-19 05:27:02.191089+00:00
[2025-08-19T05:27:08.757+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T05:27:08.761+0000] {standard_task_runner.py:63} INFO - Started process 82 to run task
[2025-08-19T05:27:08.761+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'chained_tasks_dag', 'simulate_file_confirmation', 'manual__2025-08-19T05:27:02.191089+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/chains_task_dag.py', '--cfg-path', '/tmp/tmpmi4v62q_']
[2025-08-19T05:27:08.768+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask simulate_file_confirmation
[2025-08-19T05:27:08.863+0000] {task_command.py:426} INFO - Running <TaskInstance: chained_tasks_dag.simulate_file_confirmation manual__2025-08-19T05:27:02.191089+00:00 [running]> on host e132b63b3eb0
[2025-08-19T05:27:09.032+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='chained_tasks_dag' AIRFLOW_CTX_TASK_ID='simulate_file_confirmation' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T05:27:02.191089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T05:27:02.191089+00:00'
[2025-08-19T05:27:09.036+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T05:27:09.039+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-19T05:27:09.041+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'Message saved at /tmp/***_message.txt'"]
[2025-08-19T05:27:09.062+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T05:27:09.065+0000] {subprocess.py:93} INFO - Message saved at /tmp/***_message.txt
[2025-08-19T05:27:09.066+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T05:27:09.067+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T05:27:09.109+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=chained_tasks_dag, task_id=simulate_file_confirmation, run_id=manual__2025-08-19T05:27:02.191089+00:00, execution_date=20250819T052702, start_date=20250819T052708, end_date=20250819T052709
[2025-08-19T05:27:09.139+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T05:27:09.175+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T05:27:09.178+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
